version: "3.9"

services:
  web2:
    image: nginx:1.13.0-alpine
    container_name: web2
    restart: always
    ports:
      - "3443:80"
    volumes:
      - ./web2:/var/www/html/website
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  web3:
    image: nginx:1.13.0-alpine
    container_name: web3
    restart: always
    ports:
      - "3445:80"
    volumes:
      - ./web3:/var/www/html/website
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf


  docker_proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: docker_proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/ssl:/etc/ssl/nginx
      - ./nginx/buffer:/etc/nginx/conf.d
     

networks:
  default:
    name: boy-customix
    external: true
