version: "3"
services:

  w2:
    image: compose-w2:data1
    build:
      context: ../data/w2
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # deploy:
    #   replicas: 1
    


  w3:
    image: compose-w3:data2
    build:
      context: ../data/w3
      dockerfile: Dockerfile
    ports:
     - 3001:3001
    # deploy:
    #   replicas: 1
   
    

  w4:
    image: compose-w4:data3
    build:
      context: ../data/w4
      dockerfile: Dockerfile
    ports:
     - 3002:3002
    # deploy:
    #   replicas: 1
    # port:
    #   - "3002:3002"
  # visualizer:
  #   image: dockersamples/visualizer:stable
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]

  nginx:
    image: nginx:latest
    # build:
    #   context: ./nginx
    #   dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl/nginx
    # deploy:
    #   replicas: 3